inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - 'spec/**/*'
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 125
Metrics/MethodLength:
  Max: 20
