language: ruby
sudo: false
cache: bundler
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
gemfile:
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
matrix:
 exclude:
  - rvm: 2.4.3
    gemfile: gemfiles/rails_4.0.gemfile
  - rvm: 2.4.3
    gemfile: gemfiles/rails_4.1.gemfile
  - rvm: 2.5.0
    gemfile: gemfiles/rails_4.0.gemfile
  - rvm: 2.5.0
    gemfile: gemfiles/rails_4.1.gemfile
before_install:
  - gem update --system
script:
  - bundle exec rspec
  - bundle exec rubocop -- parallel