language: ruby
sudo: false
cache: bundler
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
gemfile:
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
matrix:
 exclude:
  - rvm: 2.4.4
    gemfile: gemfiles/rails_4.0.gemfile
  - rvm: 2.4.4
    gemfile: gemfiles/rails_4.1.gemfile
  - rvm: 2.5.1
    gemfile: gemfiles/rails_4.0.gemfile
  - rvm: 2.5.1
    gemfile: gemfiles/rails_4.1.gemfile
before_install:
  - gem update --system
script:
  - bundle exec rspec
  - bundle exec rubocop -- parallel