language: ruby
sudo: false
cache: bundler
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
gemfile:
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
before_install:
  - gem update --system
script:
  - bundle install
  - bundle exec rspec
  - bundle exec rubocop -- parallel